services:
  postgres_db:
    image: postgres:18.1-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  nest_backend:
    build:
      context: .
      dockerfile: docker-files/Nest.Dockerfile
      args:
        BACKEND_PATH: ${BACKEND_PATH}
    ports:
      - "${BACKEND_PORT}:3000"
    environment:
      - DB_URL=${DB_URL}
      - BACKEND_ALLOWED_ORIGINS=${BACKEND_ALLOWED_ORIGINS}
    volumes:
      - ./backend:/app/backend
      - ./backend/node_modules:/app/backend/node_modules
    depends_on:
      postgres_db:
        condition: service_healthy

  vue_ui:
    build:
      context: .
      dockerfile: docker-files/Vue.Dockerfile
      args:
        UI_PATH: ${UI_PATH}
    ports:
      - "${UI_PORT}:5173"
    environment:
      - VITE_APP_API_URL=${VITE_APP_API_URL}
    volumes:
      - ./ui:/app/ui
      - ./ui/node_modules:/app/ui/node_modules
    depends_on:
      - nest_backend

volumes:
  db_data: